# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cube"
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["drKreso"]
  s.date = "2012-02-17"
  s.description = "Eases the pain I had to go through to get to the data out of XMLA based OLAP provider"
  s.email = "kresimir.bojcic@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "cube.gemspec",
    "lib/cube.rb",
    "lib/cube/cube.rb",
    "lib/cube/xmla.rb",
    "lib/wsdl/xmla.xml",
    "spec/cassettes/.yml",
    "spec/cassettes/kvartovi_u_recima.yml",
    "spec/cassettes/kvatovi_u_koloni.yml",
    "spec/cassettes/mondrian_broj_intervencija.yml",
    "spec/cassettes/mondrian_jedan_red_odgovor.yml",
    "spec/cassettes/mondrian_nula_redaka.yml",
    "spec/cassettes/mondrian_scalar_value.yml",
    "spec/cassettes/mondrian_vrati_samo_jedan_broj.yml",
    "spec/cassettes/razlog_prijave_i_kvart.yml",
    "spec/cube_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/drkreso/cube"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Get's the data from OLAP cube via XMLA"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<savon>, [">= 0"])
      s.add_runtime_dependency(%q<webmock>, [">= 0"])
      s.add_runtime_dependency(%q<guerrilla_patch>, [">= 0"])
      s.add_development_dependency(%q<vcr>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<savon>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<guerrilla_patch>, [">= 0"])
      s.add_dependency(%q<vcr>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<savon>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<guerrilla_patch>, [">= 0"])
    s.add_dependency(%q<vcr>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

